global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app_observability'
    metrics_path: '/api/v1/observability/metrics'
    static_configs:
      - targets: ['nginx:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'file_sd_observability'
    metrics_path: '/api/v1/observability/metrics'
    file_sd_configs:
      - files:
          - 'file_sd/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

rule_files:
  - 'rules/*.yml'
